-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 09:17:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbQuiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbQuiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbQuiz` DEFAULT CHARACTER SET utf8 ;
USE `dbQuiz` ;

-- -----------------------------------------------------
-- Table `dbQuiz`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`users` (
  `user_id` BIGINT(20) NOT NULL,
  `full_name` VARCHAR(50) NOT NULL,
  `date_of_birth` DATE NOT NULL DEFAULT 'dd/mm/yyyy',
  `email` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(50) NOT NULL,
  `is_host` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`subjects` (
  `subject_id` BIGINT(20) NOT NULL,
  `subject_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`exams` (
  `exam_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `subject_id` BIGINT(20) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `total_question` INT(5) NOT NULL DEFAULT 0,
  `total_score` INT(5) NOT NULL DEFAULT 0,
  `score_per_question` DOUBLE NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`exam_id`),
  INDEX `subjectid_fk_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `subject_fk`
    FOREIGN KEY (`subject_id`)
    REFERENCES `dbQuiz`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`rooms` (
  `room_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `exam_id` BIGINT(20) NOT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `title` VARCHAR(50) NOT NULL,
  `time_limit` INT(5) NOT NULL DEFAULT 0,
  `is_available` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`room_id`),
  INDEX `examid_fk_idx` (`exam_id` ASC) VISIBLE,
  CONSTRAINT `examid_fk`
    FOREIGN KEY (`exam_id`)
    REFERENCES `dbQuiz`.`exams` (`exam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`questions` (
  `question_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `subject_id` BIGINT(20) NOT NULL,
  `level` INT(5) NOT NULL DEFAULT 1,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `subjectid_fk_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `subjectid_fk`
    FOREIGN KEY (`subject_id`)
    REFERENCES `dbQuiz`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`question_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`question_answers` (
  `question_answer_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `question_id` BIGINT(20) NOT NULL,
  `is_correct` BIT(1) NOT NULL DEFAULT 0,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`question_answer_id`),
  INDEX `questionid_fk_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `questionid_fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `dbQuiz`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`exam_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`exam_questions` (
  `exam_question_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `exam_id` BIGINT(20) NOT NULL,
  `question_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`exam_question_id`),
  INDEX `questionid_fk_idx` (`question_id` ASC) VISIBLE,
  INDEX `examid_fk_idx` (`exam_id` ASC) INVISIBLE,
  CONSTRAINT `examid_fk1`
    FOREIGN KEY (`question_id`)
    REFERENCES `dbQuiz`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionid_fk3`
    FOREIGN KEY (`exam_id`)
    REFERENCES `dbQuiz`.`exams` (`exam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`enrollments` (
  `enrollment_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `room_id` BIGINT(20) NOT NULL,
  `score` DOUBLE NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`enrollment_id`),
  INDEX `userid_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `roomid_fk_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `userid_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbQuiz`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roomid_fk2`
    FOREIGN KEY (`room_id`)
    REFERENCES `dbQuiz`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbQuiz`.`enrollment_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbQuiz`.`enrollment_answers` (
  `enrollment_answer_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `enrollment_id` BIGINT(20) NOT NULL,
  `question_id` BIGINT(20) NOT NULL,
  `question_answer_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`enrollment_answer_id`),
  INDEX `enrollmentid_fk_idx` (`enrollment_id` ASC) VISIBLE,
  INDEX `questionid_fk_idx` (`question_id` ASC) VISIBLE,
  INDEX `questionanswerid_fk_idx` (`question_answer_id` ASC) INVISIBLE,
  CONSTRAINT `enrollmentid_fk`
    FOREIGN KEY (`enrollment_id`)
    REFERENCES `dbQuiz`.`enrollments` (`enrollment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionid_fk`
    FOREIGN KEY (`question_id`)
    REFERENCES `dbQuiz`.`questions` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionanswerid_fk`
    FOREIGN KEY (`question_answer_id`)
    REFERENCES `dbQuiz`.`question_answers` (`question_answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
